import Head from "next/head";
import profilePicture from "./profilePicture.jpeg";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="grid grid-cols-3 grid-row-2 gap-8 m-16">
        <div className="col-span-2 min-h-[300px] bg-white/[.7] rounded p-16 shadow-lg flex gap-8">
          <Image
            src={profilePicture}
            alt="Profile photo of Rachel"
            className="w-60 rounded-full"
          />
          <div>
            <h1 className="font-sans text-[#cb58e0] text-4xl font-semibold">
              Rachel Harris
            </h1>
            <h3 className="font-sans text-black text-xl font-semibold">
              Software developer
            </h3>
            <p>Perth/Remote</p>
            <h3>Culture Amp, MYOB, Elabor8, Metcash</h3>
          </div>
        </div>

        <div className="col-span-1 row-span-2 min-h-[400px] bg-white/[.7] rounded p-8 shadow-lg">
          <h2 className="font-sans text-black text-2xl font-semibold">
            Developer
          </h2>
          <p>User focused, full stack development</p>
          <p>Legacy app, green fields, features, bugs, maintenance</p>
          <p>Enterprise SAAS</p>
          <p>React, Typescript, Next.js, TailwindCSS, Ruby on Rails</p>
          <p>AWS, Buildkite, DataDog, Splunk</p>
          <p>React Testing Library, Storybook, Chromatic, Jest, Rspec</p>
        </div>

        <div className="col-span-1 min-h-[200px] bg-white/[.7] rounded p-8 shadow-lg">
          <h2 className="font-sans text-black text-2xl font-semibold">
            Product management
          </h2>
          <p>Customer interviews, User journeys</p>
          <p>Prioritisation, backlog management</p>
          <p>Working across teams</p>
        </div>

        <div className="col-span-1 min-h-[200px] bg-white/[.7] rounded p-8 shadow-lg">
          <h2 className="font-sans text-black text-2xl font-semibold">
            Software delivery
          </h2>
          <p>Agile, Cross functional team</p>
          <p>You built it, You run it</p>
        </div>
      </main>

      <footer className="flex justify-around">
        <a href="https://www.github.com/in/rachelharris90/">
          <span className="text-blue-600 underline">Github</span>
        </a>
        <a href="https://www.linkedin.com/in/harrislrachel/">
          <span className="text-blue-600 underline">LinkedIn</span>
        </a>
      </footer>
    </div>
  );
}
